version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: meetscribe-server
    ports:
      - "8081:8080"
    environment:
      # Override database path for container
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/data/meetScribe.sqlite
      # Set frontend URL for CORS
      - APP_FRONTEND_URL=http://localhost:4200
    volumes:
      # Persist database data
      - ./server/data:/app/data
      # Persist logs
      - ./server/logs:/app/logs
      # Mount secrets if they exist
      - ./server/src/main/resources/secrets.properties:/app/secrets.properties:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - meetscribe-network

networks:
  meetscribe-network:
    driver: bridge

volumes:
  server-data:
    driver: local
  server-logs:
    driver: local
