version: '3.8'

services:
  server:
    build:
      context: .
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    container_name: meetscribe-server
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/data/meetScribe.sqlite
      - APP_FRONTEND_URL=https://hackathon-jump-web-client.onrender.com
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./src/main/resources/secrets-docker.properties:/app/secrets.properties:ro
      - ./src/main/resources/secrets-docker.properties:/src/main/resources/secrets.properties:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - meetscribe-network

networks:
  meetscribe-network:
    driver: bridge

volumes:
  server-data:
    driver: local
  server-logs:
    driver: local
