version: '3.8'

services:
  server:
    image: raduandreivaida/meetscribe-server:latest  # Your private image
    platform: linux/amd64
    container_name: meetscribe-server
    ports:
      - "8080:8080"
    environment:
      # Database configuration
      - SPRING_DATASOURCE_URL=jdbc:sqlite:/app/data/meetScribe.sqlite
      
      # Frontend URL for CORS
      - APP_FRONTEND_URL=${APP_FRONTEND_URL:-https://your-frontend-domain.com}
      - APP_CORS_ALLOWED_ORIGINS=${APP_CORS_ALLOWED_ORIGINS:-https://your-frontend-domain.com}
      
      # OAuth Configuration - Set these as environment variables
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_LINKEDIN_CLIENT_ID=${LINKEDIN_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_LINKEDIN_CLIENT_SECRET=${LINKEDIN_CLIENT_SECRET}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FACEBOOK_CLIENT_ID=${FACEBOOK_CLIENT_ID}
      - SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_FACEBOOK_CLIENT_SECRET=${FACEBOOK_CLIENT_SECRET}
      
      # JWT Configuration
      - APP_SECURITY_JWT_SECRET=${JWT_SECRET}
      
      # API Keys
      - APP_RECALL_API_KEY=${RECALL_API_KEY}
      - APP_OPENAI_API_KEY=${OPENAI_API_KEY}
      
      # Application URLs
      - APP_BASE_URL=${APP_BASE_URL:-https://your-api-domain.com}
      
    volumes:
      # Persist database data
      - ./data:/app/data
      # Persist logs
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - meetscribe-network

networks:
  meetscribe-network:
    driver: bridge
